# Generated by Django 2.0.6 on 2018-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StackLike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='response',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
